"""empty message

Revision ID: 0679478187f2
Revises: 35a9d8343472
Create Date: 2025-06-22 18:01:57.306278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0679478187f2'
down_revision = '35a9d8343472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_rute', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jarak_meter', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('estimasi_detik', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('waktu_berangkat', sa.TIMESTAMP(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_rute', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_column('waktu_berangkat')
        batch_op.drop_column('estimasi_detik')
        batch_op.drop_column('jarak_meter')

    # ### end Alembic commands ###
