"""empty message

Revision ID: 2e95c69dc166
Revises: dbb1fc8beb92
Create Date: 2025-07-09 19:36:13.468476

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e95c69dc166'
down_revision = 'dbb1fc8beb92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.ENUM('admin', 'kurir'), nullable=False))

    # ### end Alembic commands ###
