"""empty message

Revision ID: 35a9d8343472
Revises: e4b268d0136d
Create Date: 2025-06-22 17:32:24.956720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35a9d8343472'
down_revision = 'e4b268d0136d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_paket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_penerima', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('latitude', sa.Double(), nullable=False))
        batch_op.add_column(sa.Column('longitude', sa.Double(), nullable=False))
        batch_op.add_column(sa.Column('kuantitas', sa.Integer(), nullable=False))
        batch_op.alter_column('resi',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Enum('di_gudang', 'berhasil', 'gagal'),
               server_default='di_gudang',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('harga')
        batch_op.drop_column('qty')
        batch_op.drop_column('lng')
        batch_op.drop_column('pengirim')
        batch_op.drop_column('penerima')
        batch_op.drop_column('no_pengirim')
        batch_op.drop_column('lat')
        batch_op.drop_column('batas_kirim')

    with op.batch_alter_table('t_rute_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waktu_tiba', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('catatan', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_rute_detail', schema=None) as batch_op:
        batch_op.drop_column('catatan')
        batch_op.drop_column('waktu_tiba')

    with op.batch_alter_table('t_paket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batas_kirim', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('lat', mysql.DOUBLE(asdecimal=True), nullable=False))
        batch_op.add_column(sa.Column('no_pengirim', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('penerima', mysql.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('pengirim', mysql.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('lng', mysql.DOUBLE(asdecimal=True), nullable=False))
        batch_op.add_column(sa.Column('qty', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('harga', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.Enum('di_gudang', 'berhasil', 'gagal'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False,
               existing_server_default=sa.text('di_gudang'))
        batch_op.alter_column('resi',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('kuantitas')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('nama_penerima')

    # ### end Alembic commands ###
