"""empty message

Revision ID: 5228100e1a78
Revises: 5c3fb9895824
Create Date: 2025-06-25 05:43:36.297490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5228100e1a78'
down_revision = '5c3fb9895824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_rute', schema=None) as batch_op:
        batch_op.add_column(sa.Column('polyline', mysql.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_rute', schema=None) as batch_op:
        batch_op.drop_column('polyline')

    # ### end Alembic commands ###
