"""empty message

Revision ID: 5553430a6538
Revises: 2e95c69dc166
Create Date: 2025-07-09 19:36:40.314813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5553430a6538'
down_revision = '2e95c69dc166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('admin', 'kurir', 'superadmin'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
