"""empty message

Revision ID: 5c3fb9895824
Revises: efd164989ce8
Create Date: 2025-06-22 22:55:05.265073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c3fb9895824'
down_revision = 'efd164989ce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_paket', schema=None) as batch_op:
        batch_op.alter_column('berat',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_paket', schema=None) as batch_op:
        batch_op.alter_column('berat',
               existing_type=sa.Integer(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)

    # ### end Alembic commands ###
