"""empty message

Revision ID: 8c2116322480
Revises: 5228100e1a78
Create Date: 2025-06-25 05:45:32.340706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c2116322480'
down_revision = '5228100e1a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_paket', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_paket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.ENUM('di_gudang', 'berhasil', 'gagal'), server_default=sa.text("'di_gudang'"), nullable=False))

    # ### end Alembic commands ###
