"""empty message

Revision ID: cb38d94f6560
Revises: 8c2116322480
Create Date: 2025-06-25 05:45:46.788463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb38d94f6560'
down_revision = '8c2116322480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_paket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('di_gudang', 'dalam_pengiriman', 'berhasil', 'gagal'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_paket', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
