"""empty message

Revision ID: e4b268d0136d
Revises: 
Create Date: 2025-06-16 09:33:52.810826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b268d0136d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_paket',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resi', sa.String(length=50), nullable=False),
    sa.Column('pengirim', sa.String(length=150), nullable=False),
    sa.Column('penerima', sa.String(length=150), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('no_pengirim', sa.String(length=20), nullable=False),
    sa.Column('no_penerima', sa.String(length=20), nullable=False),
    sa.Column('lat', sa.Double(), nullable=False),
    sa.Column('lng', sa.Double(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('harga', sa.Integer(), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('berat', sa.Double(), nullable=False),
    sa.Column('batas_kirim', sa.Date(), nullable=False),
    sa.Column('status', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resi')
    )
    op.create_table('t_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('role', sa.Enum('admin', 'kurir'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('t_rute',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kurir_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kurir_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_rute_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rute_id', sa.Integer(), nullable=False),
    sa.Column('paket_id', sa.Integer(), nullable=False),
    sa.Column('urutan', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paket_id'], ['t_paket.id'], ),
    sa.ForeignKeyConstraint(['rute_id'], ['t_rute.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_rute_detail')
    op.drop_table('t_rute')
    op.drop_table('t_user')
    op.drop_table('t_paket')
    # ### end Alembic commands ###
