"""empty message

Revision ID: efd164989ce8
Revises: 35a9d8343472
Create Date: 2025-06-22 18:04:21.346287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd164989ce8'
down_revision = '35a9d8343472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_rute', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jarak_meter', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('estimasi_detik', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('waktu_berangkat', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('waktu_selesai', sa.TIMESTAMP(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_rute', schema=None) as batch_op:
        batch_op.drop_column('waktu_selesai')
        batch_op.drop_column('waktu_berangkat')
        batch_op.drop_column('estimasi_detik')
        batch_op.drop_column('jarak_meter')

    # ### end Alembic commands ###
