"""empty message

Revision ID: f2f682920492
Revises: cb38d94f6560
Create Date: 2025-06-25 08:07:51.983790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2f682920492'
down_revision = 'cb38d94f6560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_rute', schema=None) as batch_op:
        batch_op.alter_column('jarak_meter',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_rute', schema=None) as batch_op:
        batch_op.alter_column('jarak_meter',
               existing_type=sa.Integer(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###
